### ISSUE TITLE
Github workflows

### ISSUE THREAD

**Issue by ckcollab** [ckc-org/skeletor#122]
Add this test workflow, and others, to some random directory (`skeletor_github_workflows/workflows.yml`?) and move it to `.github/workflows/` when setting up skeletor

```yaml
name: Backend tests

on: [push]

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Setup docker
        run: |
          cp .env_sample .env
          docker-compose up -d --build
      - name: Run tests
        run: docker-compose exec -T pytest

```
